Add missing header
Fix build issue:

```
/tmp/libfreefare/libfreefare/felica.c:50:16: error: implicitly declaring library
      function 'malloc' with type 'void *(unsigned long)'
      [-Werror,-Wimplicit-function-declaration]
    if ((tag = malloc(sizeof(struct felica_tag)))) {
               ^
/tmp/libfreefare/libfreefare/felica.c:50:16: note: include the header <stdlib.h>
      or explicitly provide a declaration for 'malloc'
/tmp/libfreefare/libfreefare/felica.c:64:5: error: implicit declaration of
      function 'free' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    free(tag);
    ^
2 errors generated.
```