Add missing switch case
Fix build issue:

```
/tmp/libfreefare/libfreefare/freefare.c:172:13: error: enumeration value 'NMT_BARCODE' not handled in switch
      [-Werror,-Wswitch]
    switch (tag->info.nm.nmt) {
            ^
1 error generated.
```