libfreefare/felica: Add missing header file
Fixes warning:

Scanning dependencies of target freefare
[  1%] Building C object libfreefare/CMakeFiles/freefare.dir/felica.c.o
/tmp/libfreefare/libfreefare/felica.c: In function ‘felica_tag_new’:
/tmp/libfreefare/libfreefare/felica.c:50:16: warning: implicit declaration of function ‘malloc’ [-Wimplicit-function-declaration]
     if ((tag = malloc(sizeof(struct felica_tag)))) {
                ^~~~~~
/tmp/libfreefare/libfreefare/felica.c:50:16: warning: incompatible implicit declaration of built-in function ‘malloc’
/tmp/libfreefare/libfreefare/felica.c:50:16: note: include ‘<stdlib.h>’ or provide a declaration of ‘malloc’
/tmp/libfreefare/libfreefare/felica.c:26:1:
+#include <stdlib.h>

/tmp/libfreefare/libfreefare/felica.c:50:16:
     if ((tag = malloc(sizeof(struct felica_tag)))) {
                ^~~~~~
/tmp/libfreefare/libfreefare/felica.c: In function ‘felica_tag_free’:
/tmp/libfreefare/libfreefare/felica.c:64:5: warning: implicit declaration of function ‘free’ [-Wimplicit-function-declaration]
     free(tag);
     ^~~~
/tmp/libfreefare/libfreefare/felica.c:64:5: warning: incompatible implicit declaration of built-in function ‘free’
/tmp/libfreefare/libfreefare/felica.c:64:5: note: include ‘<stdlib.h>’ or provide a declaration of ‘free’

Signed-off-by: Ricardo Ribalda Delgado <ricardo.ribalda@gmail.com>